(function() {var implementors = {};
implementors["foundationdb"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"foundationdb/struct.FdbError.html\" title=\"struct foundationdb::FdbError\">FdbError</a>",synthetic:false,types:["foundationdb::error::FdbError"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"foundationdb/options/enum.StreamingMode.html\" title=\"enum foundationdb::options::StreamingMode\">StreamingMode</a>",synthetic:false,types:["foundationdb::options::StreamingMode"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"foundationdb/options/enum.MutationType.html\" title=\"enum foundationdb::options::MutationType\">MutationType</a>",synthetic:false,types:["foundationdb::options::MutationType"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"foundationdb/options/enum.ConflictRangeType.html\" title=\"enum foundationdb::options::ConflictRangeType\">ConflictRangeType</a>",synthetic:false,types:["foundationdb::options::ConflictRangeType"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"foundationdb/options/enum.ErrorPredicate.html\" title=\"enum foundationdb::options::ErrorPredicate\">ErrorPredicate</a>",synthetic:false,types:["foundationdb::options::ErrorPredicate"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"foundationdb/tuple/struct.TupleDepth.html\" title=\"struct foundationdb::tuple::TupleDepth\">TupleDepth</a>",synthetic:false,types:["foundationdb::tuple::TupleDepth"]},];
implementors["foundationdb_sys"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"foundationdb_sys/struct.__fsid_t.html\" title=\"struct foundationdb_sys::__fsid_t\">__fsid_t</a>",synthetic:false,types:["foundationdb_sys::__fsid_t"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"foundationdb_sys/struct.FDB_future.html\" title=\"struct foundationdb_sys::FDB_future\">FDB_future</a>",synthetic:false,types:["foundationdb_sys::FDB_future"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"foundationdb_sys/struct.FDB_database.html\" title=\"struct foundationdb_sys::FDB_database\">FDB_database</a>",synthetic:false,types:["foundationdb_sys::FDB_database"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"foundationdb_sys/struct.FDB_transaction.html\" title=\"struct foundationdb_sys::FDB_transaction\">FDB_transaction</a>",synthetic:false,types:["foundationdb_sys::FDB_transaction"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"foundationdb_sys/struct.keyvalue.html\" title=\"struct foundationdb_sys::keyvalue\">keyvalue</a>",synthetic:false,types:["foundationdb_sys::keyvalue"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        })()